services:
  9gouter:
    build:
      context: .
      dockerfile: Containerfile
    image: ghcr.io/artiffusion/9gouter:latest
    container_name: 9gouter
    restart: always
    ports:
      - "20127:20127"
    volumes:
      - 9gouter-data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20127"
      HOSTNAME: "0.0.0.0"

volumes:
  9gouter-data:
    name: 9gouter-data
