services:
  9gouter:
    image: ghcr.io/artiffusion-inc/9gouter:latest
    container_name: 9gouter
    restart: always
    ports:
      - "20127:20127"
    volumes:
      - 9gouter-data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20127"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      HEADROOM_URL: http://headroom:8787
    depends_on:
      - headroom

  headroom:
    image: ghcr.io/chopratejas/headroom:latest
    container_name: headroom
    restart: always
    ports:
      - "8787:8787"

volumes:
  9gouter-data:
    name: 9gouter-data
