services:
  9router:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/artiffusion/9router:latest
    container_name: 9router
    restart: always
    ports:
      - "20127:20127"
    volumes:
      - 9router-data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "20127"
      HOSTNAME: "0.0.0.0"

volumes:
  9router-data:
    name: 9router-data
